[phases.setup]
nixPkgs = ["python311", "libffi", "opus", "gcc"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = ". /opt/venv/bin/activate && python bot.py"
